lalanguage: python
python:
  - "3.8"
  - "3.9"
  - "3.10"

# Environment setup
env:
  - TEST_ENV=dev
  - TEST_ENV=prod

# Install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov  # For coverage report
  - pip install codecov  # To upload coverage to Codecov

# Run tests and generate coverage report
script:
  - pytest --cov=your_project_name tests/  # Replace `your_project_name` with the package to test

# Upload coverage to Codecov
after_success:
  - codecov  # Requires Codecov integration

# Cache pip packages
cache: pip

# Specify branches to build
branches:
  only:
    - main
    - develop  # Add other branches as needed

# Email notifications
notifications:
  email:
    recipients:
      anguri2264@gmail.com
    on_success: never
    on_failure: always


