lalanguage: python
python:
  - "3.8"
  - "3.9"
  - "3.10"


env:
  - TEST_ENV=dev
  - TEST_ENV=prod


install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov 
  - pip install codecov  


script:
  - pytest --cov=your_project_name tests/  


after_success:
  - codecov  


cache: pip


branches:
  only:
    - main
    - develop  


notifications:
  email:
    recipients:
      anguri2264@gmail.com
    on_success: never
    on_failure: always


